

- name: Join Docker Swarm - Worker 1
  community.general.docker_swarm:
    state: join
    advertise_addr: swarm-w  
    join_token: "{{ hostvars['swarm-manager']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ "swarm-m:2377" ]




- name: Join Docker Swarm - Worker 2
  community.general.docker_swarm:
    state: join
    advertise_addr: swarm-w2  
    join_token: "{{ hostvars['swarm-manager']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ "swarm-m:2377" ]


