- name: Install Requirements for Docker
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3
      - python3-pip
    tags: docker

- name: get docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: Add docker packages to repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
  tags: docker



- name: Update apt packages
  apt:
    update_cache: "yes"
    force_apt_get: "yes"


- name: Install Docker
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: start service
  service:
    name: docker
    state: started

- name: Install Docker pip
  pip:
    executable: pip3
    name: docker
   
- name: Create docker group
  group:
    name: "docker"
    state: present

- name: Adding user  to docker group
  user:
    name: "george_rhodes"
    groups: "docker"
    append: "yes"

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
    dest: "/usr/local/bin/docker-compose"
    mode: 0755


- name: cheeky safe Reboot 
  shell: "sleep 1 && reboot"
  async: 1
  poll: 0